name: one_stop_journaling
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  bloc: ^9.0.0
  collection: ^1.19.1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_launcher_icons: ^0.14.4
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  intl: ^0.20.2
  isar_community: ^3.3.0-dev.3
  isar_community_flutter_libs: ^3.3.0-dev.3
  loader_overlay: ^5.0.0
  logger: ^2.6.1
  meta: ^1.16.0
  package_info_plus: ^9.0.0
  path_provider: ^2.1.5
  snacky: ^0.7.0
  table_calendar: ^3.2.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  # isar_generator: ^3.1.0+1
  isar_community_generator: ^3.3.0-dev.3
  build_runner: ^2.4.13
  change_app_package_name: ^1.5.0

# dependency_overrides:
#   build: ^3.0.0

flutter:
  uses-material-design: true
